% !TeX program = xelatex
% !TeX spellcheck = en_US
% !TeX encoding = UTF-8
% !Rnw weave = knitr

% BibTex Key Pattern: 
%   For Article: [auth][year][shorttitle]
%   For Book: [auth][year][title]

% C:\texlive\2020\bin\win32\tlmgr.bat update -all
% C:\texlive\2020\bin\win32\tlmgr.bat install collection-basic collection-latex collection-xetex collection-latexrecommended collection-bibtexextra collection-fontsrecommended collection-langchinese
% C:\texlive\2020\bin\win32\tlmgr.bat install enumitem float geometry listings paralist siunitx

\documentclass{article}
\usepackage{ctex}

\usepackage[left=1cm, right=1cm]{geometry}
\usepackage{float}
\usepackage{enumitem}
\usepackage{subcaption}

\usepackage{hyperref}
\hypersetup{
    pdfstartview={FitH}
}

\title{Knitr \LaTeX Template}
\author{ZHANG Yang}
\date{\today}

\begin{document}

\maketitle

\section{Environment Setup}

<<echo=TRUE, error=FALSE, warning=FALSE, message=FALSE>>=
#### Load Essential Packages ####
essential_pkgs <- c(
  "dplyr",
  "cowplot",
  "uwot",
  "ggplot2",
  "openxlsx",
  "dbplyr",
  "GenomeInfoDb",
  "readxl",
  "HDCytoData",
  "CATALYST",
  "limma",
  "diffcyt"
)

pending_pkgs <- unique(essential_pkgs[!essential_pkgs %in% installed.packages()])

if (length(pending_pkgs)) {
  if (!requireNamespace("BiocManager", quietly = TRUE)){
    install.packages("BiocManager", repos = "https://cloud.r-project.org")
  }
  BiocManager::install(pending_pkgs)
}

for(pkg in essential_pkgs) library(pkg, character.only = TRUE)
@

\section{References}

\bibliographystyle{unsrt}
\bibliography{References}

\end{document}
